package com.topie.user.persistence.domain;

// Generated by Hibernate Tools
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import com.topie.user.persistence.domain.AccountInfo;

/**
 * AttendanceInfo .
 * 
 * @author Lingo
 */
@Entity
@Table(name = "ACCOUNT_ATTENDANCE")
public class AccountAttendance implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    private Long id;
    
    /**关联的成员*/
    private AccountInfo accountInfo;
    
    /**是否工作日（1：工作日;2：休息日）*/
    private byte isDays;
    
    /**日期*/
    private String dateStr;
    
    /**星期几*/
    private String weekStr;
    
    /**应出勤工时*/
    private Float shouldAttendance;
    
    /**实际出勤工时*/
    private Float realAttendance;
    
    /**上班打卡时间*/
    private String workStartTime;
    
    /**下班打卡时间*/
    private String workEndTime;
    
	/**旷工工时*/
    private Float offHour;
    
    /**请假类型（0：正常上班;1：事假;2：病假;3：年假;4：丧假;5：看护假;6：产假;7：婚假;8：出差外勤;9：其他）*/
    private byte vacation;
    
    private String tenantId;
    
    public AccountAttendance(){}
    
    public AccountAttendance(Long id){
    	this.id = id;
    }
    
    public AccountAttendance(Long id, AccountInfo accountInfo, byte isDays,
    		String dateStr, String weekStr, Float shouldAttendance,
			Float realAttendance, String workStartTime, String workEndTime,
			Float offHour, byte vacation, String tenantId) {
		super();
		this.id = id;
		this.accountInfo = accountInfo;
		this.isDays = isDays;
		this.dateStr = dateStr;
		this.weekStr = weekStr;
		this.shouldAttendance = shouldAttendance;
		this.realAttendance = realAttendance;
		this.workStartTime = workStartTime;
		this.workEndTime = workEndTime;
		this.offHour = offHour;
		this.vacation = vacation;
		this.tenantId = tenantId;
	}
    
    @Id
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ACCOUNT_ID")
	public AccountInfo getAccountInfo() {
		return accountInfo;
	}

	public void setAccountInfo(AccountInfo accountInfo) {
		this.accountInfo = accountInfo;
	}

	@Column(name = "IS_DAYS", length = 4)
	public byte getIsDays() {
		return isDays;
	}

	public void setIsDays(byte isDays) {
		this.isDays = isDays;
	}

	@Column(name = "DATA_STR", length = 50)
	public String getDateStr() {
		return dateStr;
	}

	public void setDateStr(String dateStr) {
		this.dateStr = dateStr;
	}

	@Column(name = "WEEK_STR", length = 50)
	public String getWeekStr() {
		return weekStr;
	}

	public void setWeekStr(String weekStr) {
		this.weekStr = weekStr;
	}

	@Column(name = "SHOULD_ATTENDANCE")
	public Float getShouldAttendance() {
		return shouldAttendance;
	}

	public void setShouldAttendance(Float shouldAttendance) {
		this.shouldAttendance = shouldAttendance;
	}

	@Column(name = "REAL_ATTENDANCE")
	public Float getRealAttendance() {
		return realAttendance;
	}

	public void setRealAttendance(Float realAttendance) {
		this.realAttendance = realAttendance;
	}

	@Column(name = "WORK_START_TIME", length = 50)
	public String getWorkStartTime() {
		return workStartTime;
	}

	public void setWorkStartTime(String workStartTime) {
		this.workStartTime = workStartTime;
	}

	@Column(name = "WORK_END_TIME", length = 50)
	public String getWorkEndTime() {
		return workEndTime;
	}

	public void setWorkEndTime(String workEndTime) {
		this.workEndTime = workEndTime;
	}

	@Column(name = "OFF_HOUR")
	public Float getOffHour() {
		return offHour;
	}

	public void setOffHour(Float offHour) {
		this.offHour = offHour;
	}

	@Column(name = "VACATION", length = 4)
	public byte getVacation() {
		return vacation;
	}

	public void setVacation(byte vacation) {
		this.vacation = vacation;
	}

	@Column(name = "TENANT_ID", length = 50)
	public String getTenantId() {
		return tenantId;
	}

	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

    
    /** null. *//*
    private Long id;

    *//** null. *//*
    private String name;

    *//** null. *//*
    private Date createTime;

    *//** null. *//*
    private String status;

    *//** null. *//*
    private String type;

    *//** null. *//*
    private String catalog;

    *//** null. *//*
    private String employeeId;

    *//** null. *//*
    private String tenantId;*/

    
}
